config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/states/:id', to: 'states#show', as: 'state'
  resources :users, only: [:new, :create, :show]

end

app/models/district.rb
class District < ActiveRecord::Base
  belongs_to :state
  validates :name, uniqueness: {scope: :state, message: "should be only one district state combination"}
  def get_districts_by_state(state)
    return District.where(state: state)
  end
end

app/models/pro_publica.rb
class ProPublica
  include HTTParty
  base_uri 'https://api.propublica.org/congress/v1'
  headers "X-API-Key" => ENV["PRO_PUBLICA_API_KEY"]
  def initialize
    @congress = 115
  end

  #Below are methods that will get you data about Members of Congress.
  def get_all_members(chamber)
    self.class.get("/#{@congress}/#{chamber}/members.json")
  end

  def get_member_by_id(member_id)
    self.class.get("/members/#{member_id}.json")
  end

  def get_new_members
    self.class.get("/members/new.json")
  end

  #This will return multiple members as each state has two representatives at a minimum.
  def get_members_by_state(state, chamber)
    self.class.get("/members/#{chamber}/#{state}/current.json")
  end

  #This could return multiple members depending on the inputs.
  def get_members_by_district(state, chamber, district)
    self.class.get("/members/#{chamber}/#{state}/#{district}/current.json")
  end

  def get_members_leaving_office(congress, chamber)
    self.class.get("#{congress}/#{chamber}/members/leaving.json")
  end

  def get_member_recent_vote_positions(member_id)
    self.class.get("/members/#{member_id}/votes.json")
  end

  #Below are methods that will get you data about Votes on Bills


  #Below are methods that will get you data about Bills

  #Below are methods that will get you data about Nominations

  #State Party Counts

  #Committees and Comittee Memberships
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :districts
  def show
    @state = State.find(params[:id])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  # TODO: Figure out how we are going to reference district/state to the user. Can the user subscribe to reports of multiple district members? What if they don't specify a district?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :zip_code)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForThePeople</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/reporter/weekly_report.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Congressperson Weekly Report</title>
</head>
<body>
  Here's what your congressperson did last week.
</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |u| %>
First Name: <%= u.text_field :first_name %>

Last Name: <%= u.text_field :last_name %>

Email: <%= u.email_field :email %>

Zip Code: <%= u.text_field :zip_code %>

<%= u.submit "Sign-up" %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
Hello <%= @user.last_name %>, <%= @user.first_name %>
<br>
Welcome to ForThePeople.Vote! We hope you stay engaged politically and together we will make a difference in our community.

app/views/welcome/index.html.erb
<h1>For The People</h1>
<p>
  For The People aims to create transparency in the United States government by holding all elected officials in America accountable for representing the people they serve. 
</p>
<p>
  <%= link_to "Sign Up", new_user_path %> now to receive a weekly update on what your Members of Congress in both House and Senate have accomplished over the past week. This will include each Member's Bills proposed and Voting positions.
</p>